export const data = [
    {
        id: 1,
        name: 'Xenoblade Chronicles',
        price: 50,
        img: '',
        quantity: 1,
        description: '',
    },
    {
        id: 2,
        name: 'The Last of Us 2',
        price: 50,
        img: '',
        quantity: 1,
        description: '',
    },
    {
        id: 3,
        name: 'Super Smash Bros Ultimate',
        price: 50,
        img: '',
        quantity: 1,
        description: '',
    },
    {
        id: 4,
        name: 'Blasphemous 2',
        price: 50,
        img: '',
        quantity: 1,
        description: '',
    },
    {
        id: 5,
        name: 'Doom Eternal',
        price: 50,
        img: '',
        quantity: 1,
        description: '',
    },
    {
        id: 6,
        name: 'Xenoblade Chronicles',
        price: 50,
        img: '',
        quantity: 1,
        description: '',
    },
    {
        id: 7,
        name: 'Xenoblade Chronicles',
        price: 50,
        img: '',
        quantity: 1,
        description: '',
    },
    {
        id: 8,
        name: 'Xenoblade Chronicles',
        price: 50,
        img: '',
        quantity: 1,
        description: '',
    },
    {
        id: 9,
        name: 'Xenoblade Chronicles',
        price: 50,
        img: '',
        quantity: 1,
        description: '',
    },
    {
        id: 10,
        name: 'Xenoblade Chronicles',
        price: 50,
        urlImage: '',
        quantity: 1,
        description: '',
    },
]