export const data = [
    {
        id: 1,
        name: 'Xenoblade Chronicles X',
        price: 54.59,
        img: 'https://upload.wikimedia.org/wikipedia/en/7/7f/Xenoblade_Chronicles_X_-_Boxart.jpg',
        quantity: 1,
        description: 'Embárcate en una épica odisea de ciencia ficción en un vasto mundo abierto en el planeta Mira. Como miembro de BLADE, explora entornos alienígenas, pilota mecas gigantes llamados Skells y enfrenta criaturas colosales mientras intentas asegurar el futuro de la humanidad tras la destrucción de la Tierra.',
    },
    {
        id: 2,
        name: 'The Last of Us 2',
        price: 43.59,
        img: 'https://upload.wikimedia.org/wikipedia/en/4/4f/TLOU_P2_Box_Art_2.png',
        quantity: 1,
        description: 'Una historia intensa y emocional sobre venganza, redención y los límites de la humanidad. Ambientado en un mundo postapocalíptico devastado por una pandemia, sigue a Ellie en una travesía brutal donde cada decisión tiene un peso moral y cada encuentro deja cicatrices.',
    },
    {
        id: 3,
        name: 'Super Smash Bros Ultimate',
        price: 59.99,
        img: 'https://images.sftcdn.net/images/t_app-icon-m/p/bc408503-8b90-49da-986a-95a368bd1a1d/996290060/super-smash-bros-n4jv213CGeaYvaHmwNOpOb_X4Q0CddoA.jpg',
        quantity: 1,
        description: 'El crossover definitivo del mundo de los videojuegos. Más de 70 personajes icónicos de diferentes franquicias compiten en combates frenéticos, llenos de acción, objetos locos y escenarios memorables. ¡Todo el mundo está aquí!',
    },
    {
        id: 4,
        name: 'Blasphemous 2',
        price: 14.99,
        img: 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2114740/capsule_616x353.jpg?t=1745860287',
        quantity: 1,
        description: 'Sumérgete en un metroidvania oscuro de estética barroca y religiosa. Encarnas al Penitente en una España ficticia plagada de fanatismo, castigo divino y criaturas grotescas. Con combates desafiantes y un arte bellamente macabro, esta secuela amplía su mitología con nuevos poderes y armas.',
    },
    {
        id: 5,
        name: 'Doom Eternal',
        price: 39.99,
        img: 'https://cdn1.epicgames.com/offer/b5ac16dc12f3478e99dcfea07c13865c/EGS_DOOMEternal_idSoftware_S1_2560x1440-06b46993a4b6c19a9e614f2dd1202215',
        quantity: 1,
        description: 'Sé el DOOM Slayer y desata una carnicería infernal sin frenos. Enfréntate a hordas demoníacas con un arsenal brutal en combates frenéticos, veloces y estratégicos. La Tierra está siendo invadida, y solo tú puedes detener el Apocalipsis.',
    },
    {
        id: 6,
        name: 'Mario Kart 8 Deluxe',
        price: 59.99,
        img: 'https://www.nintendo.com/eu/media/images/10_share_images/games_15/wiiu_14/SI_WiiU_MarioKart8_image1600w.jpg',
        quantity: 1,
        description: 'La carrera definitiva de Mario y compañía. Compite en circuitos vibrantes llenos de atajos, objetos caóticos y modos para todos los niveles de habilidad. Ya sea en línea, local o en solitario, la diversión está garantizada a toda velocidad.',
    },
    {
        id: 7,
        name: 'Undertale',
        price: 9.99,
        img: 'https://preview.redd.it/undertale-fanart-by-me-hope-you-like-it-v0-8b94p4dk1n5d1.png?width=1080&crop=smart&auto=webp&s=634e0b54a980dd68fa90bdae1a38857cac8ae24b',
        quantity: 1,
        description: 'Un RPG diferente donde puedes optar por la paz o la violencia. Encuentra monstruos únicos, decisiones con peso moral y humor ingenioso en un mundo pixelado y entrañable. Cada acción cambia radicalmente el rumbo de tu aventura.',
    },
    {
        id: 8,
        name: 'Terraria',
        price: 9.99,
        img: 'https://static.wikia.nocookie.net/terrariaguia/images/6/6f/Terraria.jpg/revision/latest?cb=20211105144421&path-prefix=es',
        quantity: 1,
        description: 'Explora, construye y lucha en un mundo en 2D generado aleatoriamente. Desde cavernas llenas de tesoros hasta jefes colosales, Terraria combina exploración, crafting y combate en una experiencia infinita, tanto en solitario como en multijugador.',
    },
    {
        id: 9,
        name: 'Pokemon X',
        price: 41.49,
        img: 'https://www.nintendo.com/eu/media/images/10_share_images/games_15/nintendo_3ds_25/SI_3DS_PokemonX.jpg',
        quantity: 1,
        description: 'Descubre la región de Kalos y su belleza inspirada en Francia. Captura nuevos Pokémon, personaliza a tu entrenador y vive una aventura 3D renovada con batallas dinámicas, megaevoluciones y un enfoque más social e inmersivo.',
    },
    {
        id: 10,
        name: 'Cuphead',
        price: 19.99,
        img: 'https://meridiem-games.com/backoffice/public/uploads/games/EaRycC.jpg',
        quantity: 1,
        description: 'Un desafiante juego de acción y plataformas con un estilo visual único inspirado en los dibujos animados de los años 30. Enfrenta jefes extravagantes con precisión milimétrica mientras luchas por saldar una peligrosa deuda con el diablo.',
    },
]